### ISSUE TITLE
TODO(bep)

### ISSUE THREAD

**Issue by bep** [bep/hugoreleaser#4]
This is just a short term list to get it ready for Hugo, and does not set any scope for the future (which will be very narrow ...).

- [x] Move the `plugins` module to a new `hugoreleaser-plugins-api`.
- [x] Move the `deb` plugin to a new `hugoreleaser-archive-plugins`.
- [x] Collapse into one `--paths flag` (a slice), see below. 
- [x] Remove the `goarm` setting, that can be set in env.
- [x] Add a optional "!" (not) prefix to the Glob patterns.
- [x] Only start archive plugins on the archive step.
- [x] Add more context (e.g. number of workers to first info statement.
- [x] Make sure the simple typed flags (strings, bool etc.) are available as `HUGORELEASER_TAG` etc. in config replacements (also when they're just set as `-tag`)
- [x] Add `short_title`, `short_threshold` for release notes with a low number of changes.
- [x] Add option for a custom release notes template.
